In [2]:
import numpy as np

## Завдання 1

Вкладник поклав 50000 умовних одиниць на три різні рахунки в три різні банки. За першим рахунком виплати становитимуть 5% річних, по другому – 7% річних та по третьому 6% річних. Відомо, що через рік вкладник отримав за відсотками суму в 2250 у.о. з першого та другого банку та суму в 1400 у.о. з першого та третього банку. Скільки умовних одиниць він поклав на кожен рахунок спочатку?

##### Розв'язок

<code>Отримуємо систему рівнянь</code>

\begin{equation}
\left\{
	\begin{array}{ll}
		x + y + z = 50000 \\
		0.05x + 0.07y + 0 = 2250 \\
        0.05x + 0 + 0.06z = 1400
	\end{array}\right.
\end{equation}

In [7]:
m = np.array([[1, 1, 1],[0.05, 0.07, 0],[0.05, 0, 0.06]])
m

array([[1.  , 1.  , 1.  ],
       [0.05, 0.07, 0.  ],
       [0.05, 0.  , 0.06]])

In [26]:
s = np.array([50000, 2250, 1400])
s

array([50000,  2250,  1400])

In [27]:
deposits = np.linalg.solve(m, s)
deposits

array([10000., 25000., 15000.])

<code>Aльтернативний варіант розв'язку</code>

In [28]:
m_inv = np.linalg.inv(m)
m_inv

array([[ -1.82608696,  26.08695652,  30.43478261],
       [  1.30434783,  -4.34782609, -21.73913043],
       [  1.52173913, -21.73913043,  -8.69565217]])

In [29]:
res = m_inv.dot(s)
res

array([10000., 25000., 15000.])

## Завдання 2

На складі зберігаються мобільні телефони iPhone 6, iPhone 11, iPhone 12 моделей. Всього 1328 екземплярів. Моделей iPhone 6 на 120 менше, ніж моделей iPhone 11, та на 100 більше, ніж моделей iPhone 12. Скільки моделей кожного виду на складі?

##### Розв'язок

<code>Отримуємо систему рівнянь</code>

\begin{equation}
\left\{
	\begin{array}{ll}
		x + y + z = 1328 \\
		x - y + 0 = -120 \\
        x + 0 - z = 100
	\end{array}\right.
\end{equation}

In [9]:
con = np.array([[1, 1, 1], [1, -1, 0], [1, 0, -1]])
con

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [ 1,  0, -1]])

In [21]:
summ = np.array([1328, -120, 100])
summ

array([1328, -120,  100])

In [22]:
phones = np.linalg.solve(con, summ)
phones

array([436., 556., 336.])

<code>Aльтернативний варіант розв'язку</code>

In [31]:
con_inv = np.linalg.inv(con)
con_inv

array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.33333333,  0.33333333, -0.66666667]])

In [32]:
res_phones = con_inv.dot(summ)
res_phones

array([436., 556., 336.])

## Завдання 3

Складіть канонічне рівняння еліпсоїда, що проходить через три точки $A,B,C$
$$A(\sqrt3; 0; \sqrt3), B(\sqrt6; {1\over2}; 0), C(1 ; {1\over\sqrt3}; 1)$$
Канонічне рівняння еліпсоїда у прямокутній декартовій системі координат має вигляд:
$${x^2 \over a^2} + {y^2 \over b^2} + {z^2 \over c^2}=1$$
Завдання полягає у визначенні параметрів $a^2, b^2, c^2$

##### Розв'язок

<code>Робимо заміну</code>

$K = {1 \over a^2}; R = {1 \over b^2}; L ={1 \over c^2}$

<code>Отримуємо систему рівнянь</code>

\begin{equation}
\left\{
	\begin{array}{ll}
		3K + 0 + 3L =1 \\
		6K + {1\over4}R + 0 = 1 \\
        K + {1\over3}R + L =1
	\end{array}\right.
\end{equation}

In [46]:
matrix = np.array([[3, 0, 3], [6, 1/4, 0],[1, 1/3, 1]])
matrix

array([[3.        , 0.        , 3.        ],
       [6.        , 0.25      , 0.        ],
       [1.        , 0.33333333, 1.        ]])

In [47]:
q = np.array([1, 1, 1])
q

array([1, 1, 1])

In [50]:
coef = 1/np.linalg.solve(matrix, q)
coef

array([12. ,  0.5,  4. ])

<code>Канонічне рівняння еліпсоїда</code>

$${x^2 \over 12} + {2y^2} + {z^2 \over 4}=1$$

## Завдання 4

Складіть рівняння параболи , що проходить через задані три точки (1,12), (3,54), (-1,2). Необхідно знайти коефіцієнти рівняння a, b, c
$$y=a * x^2 + b  *x + c$$

##### Розв'язок

<code>Отримуємо систему рівнянь</code>

\begin{equation}
\left\{
	\begin{array}{ll}
		a + b + c = 12 \\
		9a + 3b + c = 54 \\
        a - b + c = 2
	\end{array}\right.
\end{equation}

In [52]:
matr = np.array([[1, 1, 1], [9, 3, 1], [1, -1, 1]])
matr

array([[ 1,  1,  1],
       [ 9,  3,  1],
       [ 1, -1,  1]])

In [53]:
y = np.array([12, 54, 2])
y

array([12, 54,  2])

In [55]:
res_coef = np.linalg.solve(matr, y)
res_coef

array([4., 5., 3.])

## Завдання 5

Складіть функцію `get_polynom`, яка за набором точок виду $(x_1,y_1),(x_2,y_2), \ldots, (x_{n+1}, y_{n+1})$ знаходитиме коефіцієнти многочлена $c_i$. Таким чином функція приймає список кортежів з координатами та повертає набір коефіцієнтів $c_0, c_1,...,c_n$


In [60]:
def get_polynom(coords):
    n = len(coords)
    a = np.zeros((n, n))
    b = np.zeros(n)
    for i in range(n):
        for j in range(n):
            a[i,j] = coords[i][0]**j
        b[i] = coords[i][1]
        
    return np.linalg.solve(a, b)

In [61]:
get_polynom([(1, 12), (3, 54), (-1, 2)])

array([3., 5., 4.])